VueDjangoTodo/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomeView.as_view(), name='home'),
    path('todo/', include('todo.urls')),
    path('api/', include('api.urls')),
]

api/urls.py
from django.urls import path
from . import views

app_name='api'

urlpatterns = [
    path('todo/list/', views.ApiTodoLV.as_view(), name='list'),
    path('todo/<int:pk>/delete/', views.ApiTodoDelV.as_view(), name='delete'),
    path('todo/create/', views.ApiTodoCV.as_view(), name='create'),
]

todo/urls.py
from django.urls import path

from . import views

app_name='todo'

urlpatterns = [
    path('', views.TodoTV.as_view(), name='index'),
]

api/models.py
from django.db import models

# Create your models here.

todo/models.py
from django.db import models

# Create your models here.
class Todo(models.Model) : 
    name = models.CharField('NAME', max_length=5, blank=True)
    todo = models.CharField('TODO', max_length=5, blank=True)

    def __str__(self) :  # 자체 이름 출력 admin에서 확인 가능
        return self.todo
    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        if(self.name == ''):
            self.name = '홍길동'
        super().save()

VueDjangoTodo/views.py
from django.views.generic import TemplateView

class HomeView(TemplateView) :
    template_name = 'home.html'

api/views.py
from django.views.generic import ListView, DeleteView, CreateView
from todo.models import Todo
from django.http import JsonResponse
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt, ensure_csrf_cookie
import json
from django.forms import model_to_dict
from django.views.generic.edit import BaseDeleteView, BaseCreateView
# Create your views here.

@method_decorator(ensure_csrf_cookie, name='dispatch') # ensure_csrf_cookie을 쓰면 csrf토큰을 만들어 리스트로 뿌립니다 즉 이걸 Vue가 받아서 axios를 다시 날려줍니다.
class ApiTodoLV(ListView) :
    
    model = Todo
    
    #def get(self, request, *args, **kwargs) :
    #   tmpList = [ 
    #        {'id': 1, 'name': 'd정승화', 'todo': 'Django와 Vue를 사용한 Todo 프로그램 제작'},
    #        {'id': 2, 'name': 'd장동건', 'todo': '굉장히 부담스럽네요'},
    #        {'id': 3, 'name': 'd원빈', 'todo': '해커톤은 처음이라서요 잘 부탁드려요'}
    #    ]
    #    return JsonResponse(data=tmpList, safe=False)

    def render_to_response(self, context, **response_kwargs) :
        todoList = list(context['object_list'].values()) # Values는 딕셔너리 형태로 변경시켜주는 역할 디장고 모델 공식문서에서 확인가능
        return JsonResponse(todoList, safe=False) # 딕셔너리가 아니면 Fasle... 이것도 장고 공식문서에서 확인이 가능한데 대체 이런걸 어떻게 알고 다 쓰는거냐고 ㅅㅂ

class ApiTodoDelV(DeleteView):
    model = Todo
    
    def delete(self, request, *args, **kwargs): 
        self.object = self.get_object()
        self.object.delete()
        return JsonResponse(data={}, status=204)

@method_decorator(csrf_exempt, name='dispatch')
class ApiTodoCV(CreateView) :
    model = Todo
    fields = '__all__'
    
    def get_form_kwargs(self) :
        kwargs = super().get_form_kwargs()
        kwargs['data'] = json.loads(self.request.body)
        return kwargs

    def form_valid(self, form) :
        self.object = form.save()
        newTodo = model_to_dict(self.object)
        return JsonResponse(data=newTodo, status=201)

    def form_invalid(self, form):
        self.request.body.decode('utf8')
        return JsonResponse(data=form.errors, status=400)

todo/views.py
from django.views.generic import TemplateView

class TodoTV(TemplateView) :
    template_name = 'todo/todo_index.html'

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css">
    <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}">
    <title>{% block title %}home.html{% endblock %}</title>

    {% block extra-style %} {% endblock %}
</head>

<body>
    
    <nav class="navbar navbar-expand-sm navbar-dark bg-primary fixed-top">

        <span class="navbar-brand mx-5 mb-0 font-weight-bold font-italic">Vue-Django System</span>
    
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav">
            <span class="navbar-toggler-icon"></span>
        </button>
    
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item mx-1 btn btn-primary">
                    <a class="nav-link text-white" href="{% url 'home' %}">Home</a></li>
                <li class="nav-item mx-1 btn btn-primary">
                    <a class="nav-link text-white" href="{% url 'todo:index' %}">Vue</a></li>
                <li class="nav-item mx-1 btn btn-primary">
                    <a class="nav-link text-white" href="{% url 'home' %}">Blog(todo)</a></li>
                <li class="nav-item dropdown mx-1 btn btn-primary">
                    <a class="nav-link dropdown-toggle text-white" href="#" data-toggle="dropdown">Util</a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="{% url 'admin:index' %}">Admin</a>
                        <div class="dropdown-divider"></div>
                    </div>
                </li>
            </ul>
    
            <form class="form-inline my-2">
                <input class="form-control mr-sm-2" type="search" placeholder="Search">
            </form>
    
            <ul class="navbar-nav ml-5 mr-5">
                <li class="nav-item dropdown mx-1 btn btn-primary">
                    <a class="nav-link dropdown-toggle text-white" href="#" data-toggle="dropdown">
                        <i class="fas fa-user"></i>&nbsp; Anonymous &nbsp;</a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="{% url 'home' %}">Login</a>
                        <a class="dropdown-item" href="{% url 'home' %}">Register</a>
                    </div>
                </li>
            </ul>
    
        </div>
    </nav>

    <div class="container">
        {% block content %} {% endblock %}
    </div>

    {% block footer %}{% endblock %}

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>

    {% block extra-script %}{% endblock %}
</body>

</html>

templates/home.html
{% extends 'base.html' %}


{% block title %} home.html {% endblock  %}
{% block extra-style %}
<style>
.wrapper{
    display: flex;
    justify-content: center;
    align-items: center;
    min-height: 100vh;
}
</style>
{% endblock  %}
{% block content %}    
    <div class='wrapper'>
        <span data-toggle="tooltip" data-placement="top" title="Tooltip on top">Tooltip on top</span>
    </div>
{% endblock  %}

{% block footer %}
{% endblock %}

{% block extra-script %}
<script>
$(function () {
	$('[data-toggle="tooltip"]').tooltip();
});
</script>
{% endblock %}

todo/templates/todo/todo_index.html
{% extends 'base.html' %}

{% block title %}Vue - Django{% endblock %}  <!--SEO문제 해결을 위해 중요한 문장을 삽입시켜주는 것이 중요 검색엔진에 노출될 수 있기 때문-->

{% block extra-style %}
<style>
.inputBox {
background-color: white;
display: flex;
border-radius: 30px;
justify-content: center;
margin:auto;
width: 80%;
height: 50%;
}

ul{
   list-style:none;
}

.inputBox__name {
border-style:none;
border-bottom:1px solid #ddd;
width: 40%;
margin-left: 20px;
}

.inputBox__todo {
border-style:none;
border-bottom:1px solid #ddd;
width: 60%;
margin-left: 10px;
}

.inputBox__add {
border-style:none;
border-bottom:1px solid #ddd;
margin-right : 20px;
width: 200px;
}

.todoList {
text-align: left;
}

.todoList li {
display: flex;
height: 50px;
line-height: 50px;
        margin: 0.5rem 0;
        padding: 0 0.9rem;
        background: white;
        border-radius: 5px;
}

.removeBtn {
margin-left: auto;
font-size: 20px;
margin-left : auto;
}

.removeBtn:hover {
    color: red;
}


body {
padding-top: 70px;
background-color: skyblue;
text-align: center;
}

</style>
{% endblock %}    

{% block content %}
    <div id='app'>
        <h1>My Todo App!</h1>

        <h5>JSH - 개발 시작 04.03 @BEM 방식 반드시 준수@</h5>
        <br>

        <div class="inputBox">
            <input class = "inputBox__name" type="text" 
                required placeholder ="name..." v-model.trim='name'>  <!--아래있는 변수와 input tag를 바인딩 해줍니다 이런 방식의 바인딩을 한다면 아래 Vue 파트와 양방향으로 정보를 주고 받을 수 있습니다.-->
            <input class = "inputBox__todo" type="text" 
                required placeholder="Enter What you want!" v-model.trim="todo" v-on:keyup.enter="add_todo"> <!--v-model은 vue다이렉트로 vue의 변수명과 Djngo 모델의 변수명과 동일합니다.  trim수식어를 사용하면 사용자가 입력한 값에서 앞뒤 공백을 제거해줍니다.-->
            <button class = "inputBox__add" v-on:click= "add_todo()">                                       <!--정정 postData의 딕셔너리와 같아야함-->
                Add</button>
        </div>

        <ul class="todoList">
            <li v-for = "(todo, index) in todoList"> <!--v-for에서 인덱스는 반드시 뒤에 옵니다.-->
                <span>[[ todo.name ]] :: [[ todo.todo ]]</span>
                <span v-on:click="remove_todo(todo, index)" class="removeBtn">&#x00D7</span>
            </li>
        </ul>

    </div>


{% endblock %}

{% block footer %} {% endblock  %}

{% block extra-script %}
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/vue@2"></script>
    <script src="https://unpkg.com/vue-router/dist/vue-router.js"></script>
    <script>
        axios.defaults.xsrfCookieName = 'csrftoken';
        axios.defaults.xsrfHeaderName = 'X-CSRFToken'; // axios 기본값 설정입니다. 
        var vm = new Vue({
            delimiters: ['[[', ']]'],
            el: '#app',
            data: {
                name : '',
                todo: '',
                todoList:[],
            },
            created: function() {
                console.log("Vue is Created")
                this.fetch_all_todo(); // 여기다가 axios를 정의하고 사용해줘도 괜찮지만 아래 methods에 따로 몰아넣는 편이 좋다. 
            }, // Vue객체가 생성되었을때 바로 실행되는 함수
            methods: {
                fetch_all_todo: function() {
                    console.log("fetch_all_todo()");
                    
                    var vm = this; // 뒤에 나올 
                    axios.get("/api/todo/list/")
                        .then(function(res) {
                            console.log('Get RES', res);
                            vm.todoList = res.data;
                        })
                        .catch(function(err) {
                            console.log('Get ERR', err);
                        })
                },
                add_todo: function() {
                    if (this.todo == '') return;
                    if (this.name == '') this.name = '홍길동';
                    console.log("할 일을 추가합니다...");
                    var vm = this;
                    var postData = {name : this.name, todo : this.todo}; // post로 보내야할 데이터는 반드시 객체 형태여야 합니다 따라서 {}를 감싸줍니다. 
                    axios.post('/api/todo/create/', postData) // post는 url뿐만 아니라 보낼 데이터도 같이 넣어주어야합니다.
                        .then(function(res) {
                            console.log('Post', res);
                            vm.todoList.push({id: res.data.id, name: res.data.name, todo: res.data.todo});   
                        })
                        .catch(function(err) {
                            console.log('Post err', err);
                        })
                    this.name ='';
                    this.todo = '';
                },

                remove_todo: function(todo, index) {
                    if (confirm('정말 삭제 하시겠습니까?') == false) return
                    var vm = this;

                    axios.delete('/api/todo/' + todo.id + '/delete/')
                        .then(function(res) {
                            console.log('할 일을 삭제 합니다...', res);
                            vm.todoList.splice(index, 1);
                        })
                        .catch(function(err) {
                            console.log('삭제에 실패 ㅠ', err);
                        })
                },
            },            
        })
    </script>
{% endblock  %}